apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: python-app   # 🔥 CRUCIAL
spec:
  selector:
    app: python-app
  ports:
    - name: http       # 🔥 CRUCIAL
      port: 80
      targetPort: 5000
